// core/src/index.ts
export { ContextClient } from "./client/context-client.js";
export type { Result, SourceFailure } from "./client/types.js";
export { CreditLedger } from "./credits/ledger.js";
export { InMemoryBudgetStore, type BudgetStore } from "./credits/budget-store.js";
export { InMemorySnapshotStore, type Snapshot, type SnapshotStore } from "./cache/snapshot-store.js";
export { hashContent } from "./cache/content-hash.js";
export { PricingTracker } from "./trackers/pricing/pricing-tracker.js";
export type { Pricing } from "./trackers/pricing/schema.js";
export { runTracker } from "./pipeline/run-tracker.js";
export type { Report } from "./report/report.js";
export type { NormalizedSnapshot, NormalizedPlan } from "./trackers/pricing/normalize.js";
export type { ReportStatus } from "./report/report.js";
export { runLandscape } from "./landscape/run-landscape.js";
export type { Landscape, PlayerProfile, ProfileFailure } from "./landscape/types.js";
export { slugify, deslugify } from "./landscape/slug.js";
export { categoryTerms, isRelevant } from "./landscape/relevance.js";
export { InMemoryLandscapeStore, type LandscapeStore } from "./cache/landscape-store.js";
export { AnthropicClient, anthropicFromEnv, type LlmClient } from "./llm/llm-client.js";
export { judgeCategoryFit } from "./landscape/category-fit.js";
export { synthesizeAnalystReport, AnalystReportSchema, type AnalystReport } from "./landscape/analyst.js";
export { computeMarketAnalytics, parsePrice } from "./landscape/analytics.js";
export type { MarketAnalytics, CapabilityCoverage, PricingStats, CompositionStats } from "./landscape/analytics.js";
export { snapshotLandscape, diffLandscapes } from "./landscape/diff.js";
export type { LandscapeSnapshot, PlayerSnapshot, LandscapeDiff, PricingChange, CapabilityChange } from "./landscape/diff.js";
export { buildMotionTimeline, diffToMarkdown, type MotionEntry } from "./landscape/motion.js";
